name: deploy-toy-website-end-to-end
concurrency: toy-company

on: 
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:

  # Build the app and db.
  build:
    uses: rfrazier/ghdeploymentse2e/.github/workflows/build.yml@main

  # Lint the Bicep file.
  lint:
    uses: rfrazier/ghdeploymentse2e/.github/workflows/lint.yml@main

  # Deploy to the test environment.
  deploy-test:
    uses: rfrazier/ghdeploymentse2e/.github/workflows/deploy.yml@main
    needs: [build, lint]
    with:
      environmentType: Test
      resourceGroupName: GHDeploymentsE2E_Test
      reviewApiUrl: https://sandbox.contoso.com/reviews
      sqlServerAdministratorLogin: TestToyCompanyAdmin
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS_TEST }}
      reviewApiKey: ${{ secrets.REVIEW_API_KEY_TEST }}
      sqlServerAdministratorLoginPassword: ${{ secrets.SQL_SERVER_ADMINISTRATOR_LOGIN_PASSWORD_TEST }}

  # Deploy to the production environment.
  deploy-production:
    uses: rfrazier/ghdeploymentse2e/.github/workflows/deploy.yml@main
    needs: [build, lint, deploy-test]
    with:
      environmentType: Production
      resourceGroupName: GHDeploymentsE2E_Prod
      reviewApiUrl: https://api.contoso.com/reviews
      sqlServerAdministratorLogin: ToyCompanyAdmin
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS_PROD }}
      reviewApiKey: ${{ secrets.REVIEW_API_KEY_PRODUCTION }}
      sqlServerAdministratorLoginPassword: ${{ secrets.SQL_SERVER_ADMINISTRATOR_LOGIN_PASSWORD_PRODUCTION }}
